**NumPy**:Numerical Python

**Advantages of Numpy arrays**:

1.   Allows several Mathematical Operations
2.   Faster operations





In [1]:
import numpy as np

**List vs Numpy**:Time Taken

In [2]:
from time import process_time

Time Taken by List

In [5]:
Python_list=[i for i in range(10000)]
start_time = process_time()
Python_list = [i+5 for i in Python_list]
end_time = process_time()
print(end_time - start_time)

0.0014631190000002903


Numpy Array

In [6]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5  
end_time = process_time()
print(end_time - start_time)

0.0016200179999996678


Numpy Array

In [7]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
# creating a 1 dimension array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
a.shape

(4,)

In [11]:
# creating 2 dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b.shape

(2, 4)

In [13]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [15]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.61814886 0.54394367 0.86959731 0.90554753]
 [0.77940044 0.31869895 0.08898243 0.56247712]
 [0.70561139 0.03498048 0.87794402 0.35555028]]


In [20]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[23 27 76 19 95]
 [56 40 12 15 65]
 [24 36 23 58 23]]


In [21]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [22]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [23]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [24]:
c = np.random.randint(10,90,(5,5))
print(c)

[[24 29 64 36 12]
 [53 35 67 23 71]
 [12 58 37 56 42]
 [57 18 21 43 36]
 [21 40 76 56 40]]


In [25]:
# array dimension
print(c.shape)

(5, 5)


In [26]:
# number of dimensions
print(c.ndim)

2


In [27]:
# number of elements in an array
print(c.size)

25


In [28]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [29]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [30]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 2 6]
 [9 0 1]
 [8 0 1]]
[[19 12 19]
 [12 11 12]
 [14 15 16]]


In [31]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 14 25]
 [21 11 13]
 [22 15 17]]
[[-18 -10 -13]
 [ -3 -11 -11]
 [ -6 -15 -15]]
[[ 19  24 114]
 [108   0  12]
 [112   0  16]]
[[0.05263158 0.16666667 0.31578947]
 [0.75       0.         0.08333333]
 [0.57142857 0.         0.0625    ]]


In [32]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 1 8]
 [1 1 5]
 [3 5 5]]
[[15 11 18]
 [14 19 12]
 [18 10 10]]


In [33]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 12 26]
 [15 20 17]
 [21 15 15]]
[[ -7 -10 -10]
 [-13 -18  -7]
 [-15  -5  -5]]
[[120  11 144]
 [ 14  19  60]
 [ 54  50  50]]
[[0.53333333 0.09090909 0.44444444]
 [0.07142857 0.05263158 0.41666667]
 [0.16666667 0.5        0.5       ]]


Array Manipulation

In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 0 5]
 [2 0 3]]
(2, 3)


In [35]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 2]
 [0 0]
 [5 3]]
(3, 2)


In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 4 3]
 [3 3 1]]
(2, 3)


In [37]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 3]
 [4 3]
 [3 1]]
(3, 2)


In [38]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 7 5]
 [6 2 3]]
(2, 3)


In [39]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 7]
 [5 6]
 [2 3]]
(3, 2)
